---

image: docker:dind

stages:
  - release

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD CI_REGISTRY_IMAGE

release: 
  stage: release
  script: 
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
